---
- name: Disallow root login remotely
  command: 'mysql -u root -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
  become: yes
  become_user: "{{ cmon_ssh_user }}"

- name: Get list of hosts for the root user.
  command: mysql -u root -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mysql_root_hosts
  changed_when: false
  become: yes
  become_user: "{{ cmon_ssh_user }}"

- name: Check if root password has been configured.
  stat: path="{{ mysql_user_home }}/.my.cnf"
  register: root_password_configured

- name: Update MySQL root password for localhost root account.
  shell: >
    mysql -u root -NBe
    'SET PASSWORD FOR "{{ mysql_root_username }}"@"{{ item }}" = PASSWORD("{{ mysql_root_password }}");'
  with_items: "{{ mysql_root_hosts.stdout_lines }}"
  when: root_password_configured.stat.exists == false
  become: yes
  become_user: "{{ cmon_ssh_user }}"

- name: Copy .my.cnf file with root password credentials.
  template:
    src: "user-my.cnf.j2"
    dest: "{{ mysql_user_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600

- name: Get list of hosts for the anonymous user.
  command: mysql -u root -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false
  become: yes

- name: Remove anonymous MySQL users.
  mysql_user:
    login_host: localhost
    config_file: "{{ mysql_user_home }}/.my.cnf"
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"
  become: yes

- name: Remove MySQL test database.
  mysql_db:
    login_host: localhost
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
    name: "test"
    state: absent
  become: yes
  become_user: "{{ cmon_ssh_user }}"

- name: Check if ClusterControl Controller database is exist.
  command: mysqlshow -u root 'cmon' 'hosts'
  register: cmon_db
  ignore_errors: yes
  become: yes

- name: Check if ClusterControl UI database is exist.
  command: mysqlshow -u root 'dcps' 'apis'
  register: dcps_db
  ignore_errors: yes
  become: yes
  become_user: "{{ cmon_ssh_user }}"

- name: Import ClusterControl Controller database.
  shell:
    mysql -u root < "{{ cmon_sql_path }}/cmon_db.sql" &&
    mysql -u root < "{{ cmon_sql_path }}/cmon_data.sql"
  register: cmon_db_import
  when: "'Unknown' in cmon_db.stderr"
  become: yes
  become_user: "{{ cmon_ssh_user }}"

- name: Import ClusterControl UI database.
  shell: mysql -u root < {{ apache_doc_root }}/clustercontrol/sql/dc-schema.sql
  register: ccui_db_import
  when:
    ("'Unknown' in dcps_db.stderr") or
    (rh_clustercontrol_ui_install_packages.changed) or
    (deb_clustercontrol_ui_install_packages.changed)
  become: yes
  become_user: "{{ cmon_ssh_user }}"

